# Generated by Django 6.0.4 on 2026-05-31 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='last_name',
        ),
    ]
